android_library(
    name = "animals",
    manifest = "manifest.xml",
    srcs = glob(["*.java"]),
    deps = [
        "//src/com/facebook/example/animals/jni:jni",
        "//src/com/facebook/example/habitat:habitat",
        "//src/com/facebook/example/mammals:mammals",
        "//src/com/facebook/soloader:soloader",
    ],
    visibility = ["PUBLIC"],
)
