java_library(
    name = "habitat",
    srcs = glob(["*.java"]),
    deps = [
        "//src/com/facebook/example/habitat/jni:jni",
        "//src/com/facebook/soloader:soloader",
    ],
    visibility = ["PUBLIC"],
)
