include_defs("//bucklets/DEFS")

my_cxx_library(
    name = "jni",
    soname = "libmammals.$(ext)",
    allow_jni_merging = True,
    srcs = glob(["*.c"]),
    visibility = [
        "//src/com/facebook/example/mammals:mammals",
    ],
)
